[env:viewe_smartring]
platform = espressif32@6.9.0
board = lolin_s3_pro
framework = arduino

monitor_speed = 115200
upload_port = COM4
monitor_port = COM5

board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DVIEWE_SMARTRING=1

lib_deps =
    moononournation/GFX Library for Arduino@1.5.7
    lewisxhe/SensorLib@0.3.1
    h2zero/NimBLE-Arduino@^1.4.2